import Foundation
import PDFKit
import UIKit
import Vision

/// Reads the words out of a document.
///
/// A PDF generated by an insurer carries a real text layer, and pulling it out
/// is exact. A photographed or scanned one carries nothing but pixels, so it
/// goes through Vision instead. Both paths run entirely on the device — no
/// document ever leaves the phone to be read.
enum TextRecognizer {

    /// Text from a PDF: the embedded layer if there is one, OCR if there isn't.
    static func text(fromPDF data: Data) async -> String {
        if let document = PDFDocument(data: data),
           let embedded = document.string?.trimmingCharacters(in: .whitespacesAndNewlines),
           embedded.count > 80 {
            return embedded
        }
        let images = PDFBuilder.pageImages(from: data)
        return await text(from: images)
    }

    static func text(from images: [UIImage]) async -> String {
        var pages: [String] = []
        for image in images {
            if let page = await recognize(image), !page.isEmpty { pages.append(page) }
        }
        return pages.joined(separator: "\n")
    }

    /// One image through Vision's accurate recogniser.
    static func recognize(_ image: UIImage) async -> String? {
        guard let cgImage = image.cgImage else { return nil }

        return await withCheckedContinuation { continuation in
            let request = VNRecognizeTextRequest { request, _ in
                let observations = request.results as? [VNRecognizedTextObservation] ?? []
                let lines = observations.compactMap { $0.topCandidates(1).first?.string }
                continuation.resume(returning: lines.joined(separator: "\n"))
            }
            request.recognitionLevel = .accurate
            request.usesLanguageCorrection = true
            // Indian paperwork is overwhelmingly English, and adding scripts
            // Vision must disambiguate between makes it slower and no better.
            request.recognitionLanguages = ["en-IN", "en-US"]

            let handler = VNImageRequestHandler(cgImage: cgImage, options: [:])
            DispatchQueue.global(qos: .userInitiated).async {
                do {
                    try handler.perform([request])
                } catch {
                    continuation.resume(returning: nil)
                }
            }
        }
    }

    /// Trimmed to what an item record can reasonably carry.
    static func capped(_ text: String) -> String {
        let cleaned = text
            .replacingOccurrences(of: "\r", with: "\n")
            .replacingOccurrences(of: "[ \\t]+", with: " ", options: .regularExpression)
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard cleaned.count > ItemAttachment.maximumExtractedCharacters else { return cleaned }
        return String(cleaned.prefix(ItemAttachment.maximumExtractedCharacters))
    }
}
